### ISSUE TITLE
Display footprint request

### ISSUE THREAD

**Issue by bosiden** [HX2003/reflow_oven_lvgl_codeblocks_simulator#2]
Hi!

First of all thanks for the great contribution, I'm working on a project using the same round display you have on your youtube video.

Would you mind sharing the Eagle Footprint of the display? I'm designing my own PCB as well and that would help me a lot.

Thanks again in advance!

**Comment by HX2003** [comment]
Well, I don't have the Eagle Footprint as I'm using EasyEDA. Thankfully, the FPC footprint of the GC9A01 is completely identical to the ST7789. Maybe this will work: https://github.com/adafruit/Adafruit-1.54-inch-240x240-TFT-PCB (12 pin version).

**Comment by bosiden** [comment]
Thanks, I'm going to take a look at it.
