### ISSUE TITLE
[Request] Esp32 implementation

### ISSUE THREAD

**Issue by bosiden** [HX2003/reflow_oven_lvgl_codeblocks_simulator#3]
Hello,

Great project and really nice UI, could you share your ESP32 implementation?
Thanks!

**Comment by HX2003** [comment]
Hi again, thanks for your interest in this!
I have uploaded the [main sketch](https://github.com/HX2003/reflow_oven_esp32) and also put up some [basic instructions and diagrams](https://hackaday.io/project/175668-reflow-oven) if you do intend to use the ESP32.
